USE [master]
GO

/****** Object:  Database [TesteGlobal5]    Script Date: 12/08/2024 19:39:52 ******/
CREATE DATABASE [TesteGlobal5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TesteGlobal5', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TesteGlobal5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TesteGlobal5_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TesteGlobal5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TesteGlobal5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TesteGlobal5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TesteGlobal5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TesteGlobal5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TesteGlobal5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TesteGlobal5] SET ARITHABORT OFF 
GO

ALTER DATABASE [TesteGlobal5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TesteGlobal5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TesteGlobal5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TesteGlobal5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TesteGlobal5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TesteGlobal5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TesteGlobal5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TesteGlobal5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TesteGlobal5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TesteGlobal5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TesteGlobal5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TesteGlobal5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TesteGlobal5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TesteGlobal5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TesteGlobal5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TesteGlobal5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TesteGlobal5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TesteGlobal5] SET RECOVERY FULL 
GO

ALTER DATABASE [TesteGlobal5] SET  MULTI_USER 
GO

ALTER DATABASE [TesteGlobal5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TesteGlobal5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TesteGlobal5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TesteGlobal5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TesteGlobal5] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TesteGlobal5] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TesteGlobal5] SET QUERY_STORE = ON
GO

ALTER DATABASE [TesteGlobal5] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TesteGlobal5] SET  READ_WRITE 
GO


CREATE TABLE [dbo].[FORNECEDOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CNPJ] [nchar](20) NULL,
	[RAZAOSOCIAL] [nchar](80) NULL
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[ESTOQUE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA_ENTRADA] [datetime] NULL,
	[FORNECEDOR_ID] [int] NULL,
	[MATERIAL_ID] [int] NULL,
	[TIPO_ENTRADA] [nchar](10) NULL,
	[QUANTIDADE] [int] NULL,
	[VALOR] [decimal](18, 2) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[MATERIAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [nchar](20) NULL,
	[NOME] [nchar](50) NULL
) ON [PRIMARY]
GO

CREATE proc [sp_ConsultaEstoque]
as
select * from estoque e inner join fornecedor f on e.fornecedor_id=f.id inner join material m on e.material_id=m.id 

GO

create proc [sp_ConsultaFornecedor]
as
select * from FORNECEDOR

GO

create proc [sp_ConsultaMaterial]
as
select * from MATERIAL

GO

create proc [sp_DeleteEstoque] @id int
as
delete from ESTOQUE where ID=@ID

GO

create proc [sp_DeleteFornecedor] @id int
as 
delete from FORNECEDOR where ID=@ID

GO

create proc [sp_DeleteMaterial] @id int
as
delete from MATERIAL where ID=@id

GO

create procedure [sp_EditarEstoque] @VALOR DECIMAL, @QUANTIDADE INT,
@TIPO_ENTRADA NVARCHAR(10),@MATERIAL_ID INT, @FORNECEDOR_iD INT, @DATA_ENTRADA datetime,@ID int 
as
update ESTOQUE set VALOR=@VALOR , QUANTIDADE=@QUANTIDADE, 
TIPO_ENTRADA=@TIPO_ENTRADA, MATERIAL_ID=@MATERIAL_ID, FORNECEDOR_ID=@FORNECEDOR_ID, DATA_ENTRADA=@DATA_ENTRADA where ID=@ID;

GO

create proc [sp_EditarFornecedor] @ID INT, @CNPJ NVARCHAR(20),@RAZAOSOCIAL NVARCHAR(80)
AS
UPDATE FORNECEDOR SET CNPJ=@CNPJ, RAZAOSOCIAL=@RAZAOSOCIAL WHERE ID=@ID

GO

CREATE PROC [sp_EditarMaterial]
 @CODIGO nvarchar(20), @NOME NVARCHAR(50),@ID int
as
update material set CODIGO=@CODIGO , NOME=@NOME where ID=@ID

GO

create proc [Sp_IncluirEstoque] @DATA_ENTRADA DATETIME, @MATERIAL_ID INT,
@FORNECEDOR_ID INT,@TIPO_ENTRADA NVARCHAR(10),@VALOR DECIMAL,@QUANTIDADE INT
as
insert into ESTOQUE (DATA_ENTRADA,MATERIAL_ID,FORNECEDOR_ID,TIPO_ENTRADA,VALOR,QUANTIDADE) 
values (@DATA_ENTRADA,@MATERIAL_ID,@FORNECEDOR_ID,@TIPO_ENTRADA,@VALOR,@QUANTIDADE)

GO

create proc [sp_IncluirFornecedor] @CNPJ nvarchar(20),@RAZAOSOCIAL NVARCHAR(80)
AS
insert into FORNECEDOR (CNPJ,RAZAOSOCIAL) values (@CNPJ,@RAZAOSOCIAL)

GO

create proc [sp_IncluirMaterial] @CODIGO NVARCHAR(10),@NOME NVARCHAR(50)
as
insert into MATERIAL (CODIGO, NOME) values (@CODIGO,@NOME)

GO

CREATE procedure [sp_Relatorio] @TIPO_ENTRADA NVARCHAR(10),@MATERIAL_ID INT,
@FORNECEDOR_ID INT,@DATA_INICIAL DATETIME,@DATA_FINAL DATETIME
as
select * from estoque e inner join fornecedor f on
 e.fornecedor_id=f.id inner join material m on e.material_id=m.id
 where (e.DATA_ENTRADA between @DATA_INICIAL and @DATA_FINAL) and
  (e.FORNECEDOR_ID=@FORNECEDOR_ID or @FORNECEDOR_ID=@FORNECEDOR_ID) 
  and (e.MATERIAL_ID=@MATERIAL_ID or @MATERIAL_ID=@MATERIAL_ID)
GO